name: Main workflow
on: [push]
jobs:
  main-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn test
